### PR TITLE
Implemented footers. 

### PR DESCRIPTION
**Pull request by oxelf**
In this PR, I've added 3 kinds of footers, simple, logo and sitemap.

This is the design: https://www.material-tailwind.com/docs/react/footer#

My Implemented Versions:

### Simple

https://github.com/opxica/modular-ui/assets/110409182/72c85e02-cfa8-4d82-8660-b8c0d288064d

### Logo

https://github.com/opxica/modular-ui/assets/110409182/73819158-e63f-4eb3-8ed5-7dcfdcd5ae69

### Sitemap

https://github.com/opxica/modular-ui/assets/110409182/cea3fdc4-88f2-40c5-a61e-ae3307273c15

### CODE REVIEW

**Comment by Utkarsh4517** [comment]
Do we really need footers in a mobile app?

**Comment by Utkarsh4517** [comment]
Thank you for your valuable contributions @oxelf

**Comment by oxelf** [comment]
Im really having a lot of fun working on this project

**Comment by Utkarsh4517** [comment]
Thank you for your valuable contributions. 😍

**Pull request merged**
